# Generated by Django 4.2.4 on 2023-08-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programmer',
            old_name='fullanem',
            new_name='fullname',
        ),
        migrations.AlterField(
            model_name='programmer',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
